import { createHash } from "node:crypto";
export type NormalizationInput={country:string;city:string;district:string;transaction:"sale"|"rent";propertyType:"condo"|"house"|"villa";price:number;currency:"USD";areaSqm:number;bedrooms:number;bathrooms:number;title:string;summary:string;sourceExternalKey:string;sourceUrl:string;observedAt:string};
export type NormalizedListing={country:string;countryCode:string;city:string;district:string;transaction:"sale"|"rent";propertyType:"condo"|"house"|"villa";priceMinor:number;currency:"USD";areaSqmX100:number;bedrooms:number;bathrooms:number;title:string;summary:string;source:{externalKey:string;url:string};observedAt:string;fingerprint:string;normalizedHash:string};
const countries=new Map([["kh",["Cambodia","KH"]],["cambodia",["Cambodia","KH"]],["id",["Indonesia","ID"]],["indonesia",["Indonesia","ID"]],["la",["Laos","LA"]],["laos",["Laos","LA"]],["my",["Malaysia","MY"]],["malaysia",["Malaysia","MY"]],["mm",["Myanmar","MM"]],["myanmar",["Myanmar","MM"]],["ph",["Philippines","PH"]],["philippines",["Philippines","PH"]],["sg",["Singapore","SG"]],["singapore",["Singapore","SG"]],["th",["Thailand","TH"]],["thailand",["Thailand","TH"]],["vn",["Vietnam","VN"]],["vietnam",["Vietnam","VN"]]]);
const email=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i;const phone=/(?:^|[^\d])\+?\d[\d\s().-]{6,}\d(?:$|[^\d])/;
function text(value:unknown,name:string,min=1,max=2048){if(typeof value!=="string")throw new TypeError(`${name} must be a string`);const clean=value.normalize("NFKC").trim().replace(/\s+/g," ");if(clean.length<min||clean.length>max)throw new RangeError(`${name} length is invalid`);return clean}
function publicText(value:unknown,name:string,min:number,max:number){const clean=text(value,name,min,max);if(email.test(clean)||phone.test(clean))throw new Error(`${name} must not contain contact information`);return clean}
function scaled(value:unknown,name:string,scale:number,max:number){if(typeof value!=="number"||!Number.isFinite(value)||value<=0||value>max)throw new RangeError(`${name} must be a positive finite number`);const result=Math.round(value*scale);if(Math.abs(value*scale-result)>Number.EPSILON*Math.max(1,result)*4)throw new RangeError(`${name} must have no more than two decimal places`);return result}
function count(value:unknown,name:string){if(!Number.isInteger(value)||(value as number)<0||(value as number)>100)throw new RangeError(`${name} must be an integer between 0 and 100`);return value as number}
function digest(namespace:string,value:unknown){return createHash("sha256").update(namespace).update("\0").update(JSON.stringify(value,Object.keys(value as object).sort())).digest("hex")}
export function normalizeApprovedFixture(input:unknown):NormalizedListing{
 if(!input||typeof input!=="object"||Array.isArray(input))throw new TypeError("listing input must be an object");const row=input as Record<string,unknown>;const countryEntry=countries.get(text(row.country,"country",2,60).toLowerCase());if(!countryEntry)throw new RangeError("country must be supported");
 const [country,countryCode]=countryEntry;const city=text(row.city,"city",2,100);const district=text(row.district,"district",1,120);if(!["sale","rent"].includes(row.transaction as string))throw new RangeError("transaction must be sale or rent");if(!["condo","house","villa"].includes(row.propertyType as string))throw new RangeError("propertyType is unsupported");if(row.currency!=="USD")throw new RangeError("currency must be USD");
 const priceMinor=scaled(row.price,"price",100,100_000_000),areaSqmX100=scaled(row.areaSqm,"areaSqm",100,1_000_000),bedrooms=count(row.bedrooms,"bedrooms"),bathrooms=count(row.bathrooms,"bathrooms"),title=publicText(row.title,"title",3,200),summary=publicText(row.summary,"summary",10,2000),externalKey=text(row.sourceExternalKey,"sourceExternalKey",1,256);const source=new URL(text(row.sourceUrl,"sourceUrl",10,2048));if(source.protocol!=="https:"||source.username||source.password||source.hash)throw new Error("sourceUrl must use HTTPS and contain no credentials or fragment");for(const [key,value] of source.searchParams)if(/contact|email|phone|tel|whatsapp/i.test(key)||email.test(value))throw new Error("sourceUrl must not contain contact information");const observed=Date.parse(text(row.observedAt,"observedAt"));if(!Number.isFinite(observed))throw new RangeError("observedAt must be valid");const core={areaSqmX100,bedrooms,city:city.toLowerCase(),countryCode,district:district.toLowerCase(),priceMinor};const payload={country,countryCode,city,district,transaction:row.transaction,propertyType:row.propertyType,priceMinor,currency:"USD",areaSqmX100,bedrooms,bathrooms,title,summary,source:{externalKey,url:source.toString()}};
 return {...payload,transaction:row.transaction as "sale"|"rent",propertyType:row.propertyType as "condo"|"house"|"villa",observedAt:new Date(observed).toISOString(),fingerprint:digest("gli-listing-fingerprint:v1",core),normalizedHash:digest("gli-normalized-listing:v1",payload)};
}
