import type { Asset, AssetCategory } from "./assets";
import { partnerAssets } from "./partner-assets.ts";

export const curatedOpportunities: Asset[] = [
  ...partnerAssets,
  {
    id: "GLI-CM-KH-201",
    country: "Cambodia",
    countryCode: "KH",
    city: "Phnom Penh",
    district: "Tonle Bassac",
    transaction: "sale",
    propertyType: "house",
    assetCategory: "commercial",
    categoryLabel: "상업용",
    offerLabel: "매각 제안",
    priceLabel: "$1,250,000",
    cardMeta: "리테일 포디움 · 연면적 1,480㎡",
    bedrooms: 0,
    bathrooms: 6,
    title: "Phnom Penh riverside retail podium",
    price: 1250000,
    currency: "USD",
    areaSqm: 1480,
    image:
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=84",
    summary:
      "톤레바삭 생활권의 상업시설 운영 및 매각 검토 자산입니다. 임차 현황과 운영비, 권리 자료는 관심 등록 이후 GLI 조사 항목으로 관리합니다.",
    trustScore: 78,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    updatedAt: "2026-07-30T10:00:00+07:00",
    detailFacts: [
      { label: "자산 유형", value: "리테일 포디움" },
      { label: "연면적", value: "1,480㎡" },
      { label: "임차 현황", value: "조사 예정" },
      { label: "운영비", value: "조사 예정" },
    ],
    strengths: ["도심 핵심 생활권", "복합 상업 운영 가능성", "GLI 직접 조사 후보"],
    checks: ["임대차 현황", "권리 및 담보", "시설 운영비"],
  },
  {
    id: "GLI-CM-VN-202",
    country: "Vietnam",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    district: "District 1",
    transaction: "sale",
    propertyType: "house",
    assetCategory: "commercial",
    categoryLabel: "상업용",
    offerLabel: "지분 협의",
    priceLabel: "$780,000부터",
    cardMeta: "서비스드 오피스 · 운영형 자산",
    bedrooms: 0,
    bathrooms: 4,
    title: "District 1 serviced office floor",
    price: 780000,
    currency: "USD",
    areaSqm: 920,
    image:
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=84",
    summary:
      "호찌민 1군의 서비스드 오피스 운영 참여 후보입니다. 운영사 계약, 실가동률과 현지 투자 구조는 GLI의 후속 조사 대상으로 구성됩니다.",
    trustScore: 75,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    updatedAt: "2026-07-26T09:00:00+07:00",
    detailFacts: [
      { label: "자산 유형", value: "서비스드 오피스" },
      { label: "운영 면적", value: "920㎡" },
      { label: "가동률", value: "조사 예정" },
      { label: "운영 계약", value: "조사 예정" },
    ],
    strengths: ["호찌민 중심 업무지구", "운영형 수익 구조", "현지 파트너 협의 후보"],
    checks: ["투자 구조", "운영사 계약", "실가동률"],
  },
  {
    id: "GLI-LS-KH-301",
    country: "Cambodia",
    countryCode: "KH",
    city: "Siem Reap",
    district: "Wat Bo",
    transaction: "sale",
    propertyType: "villa",
    assetCategory: "leisure",
    categoryLabel: "레저",
    offerLabel: "운영권 제안",
    priceLabel: "$2,400,000",
    cardMeta: "부티크 리조트 · 28객실",
    bedrooms: 28,
    bathrooms: 30,
    title: "Siem Reap boutique resort opportunity",
    price: 2400000,
    currency: "USD",
    areaSqm: 3600,
    image:
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=84",
    summary:
      "시엠립 관광 생활권의 부티크 리조트 운영 검토 기회입니다. 객실 실적과 시설 상태, 운영권 범위는 관심 등록 후 현지 확인이 필요합니다.",
    trustScore: 80,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    updatedAt: "2026-07-31T11:00:00+07:00",
    detailFacts: [
      { label: "시설 유형", value: "부티크 리조트" },
      { label: "객실", value: "28실" },
      { label: "최근 가동률", value: "조사 예정" },
      { label: "운영권 범위", value: "조사 예정" },
    ],
    strengths: ["관광 중심 생활권", "운영 중 시설 후보", "현장 실사 연계 가능"],
    checks: ["최근 객실 실적", "시설 보수 범위", "운영권 계약"],
  },
  {
    id: "GLI-LS-PH-302",
    country: "Philippines",
    countryCode: "PH",
    city: "Puerto Princesa",
    district: "Palawan",
    transaction: "rent",
    propertyType: "villa",
    assetCategory: "leisure",
    categoryLabel: "레저",
    offerLabel: "장기 운영 협의",
    priceLabel: "조건 협의",
    cardMeta: "에코 롯지 · 운영 파트너십",
    bedrooms: 18,
    bathrooms: 20,
    title: "Palawan eco-lodge operating partnership",
    price: 0,
    currency: "USD",
    areaSqm: 5100,
    image:
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=84",
    summary:
      "팔라완 자연 관광권의 에코 롯지 운영 파트너십 후보입니다. 계약 기간, 환경 인허가와 운영 실적은 GLI 조사 후 구체화할 예정입니다.",
    trustScore: 70,
    trustStatus: "PRELIMINARY",
    isGliDirect: true,
    updatedAt: "2026-07-20T09:00:00+07:00",
    detailFacts: [
      { label: "시설 유형", value: "에코 롯지" },
      { label: "객실", value: "18실" },
      { label: "계약 기간", value: "조사 예정" },
      { label: "환경 인허가", value: "조사 예정" },
    ],
    strengths: ["자연 관광 수요", "운영 파트너십 구조", "확장 가능 부지 후보"],
    checks: ["환경 인허가", "운영 계약 기간", "최근 매출 자료"],
  },
  {
    id: "GLI-PJ-KH-401",
    country: "Cambodia",
    countryCode: "KH",
    city: "Phnom Penh",
    district: "BKK1",
    transaction: "sale",
    propertyType: "house",
    assetCategory: "project",
    categoryLabel: "프로젝트",
    offerLabel: "사업 참여",
    priceLabel: "$220,000 참여금",
    cardMeta: "프리미엄 다이닝 · 운영 프로젝트",
    bedrooms: 0,
    bathrooms: 0,
    title: "Phnom Penh premium dining project",
    price: 220000,
    currency: "USD",
    areaSqm: 0,
    image:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=84",
    summary:
      "프놈펜 핵심 생활권에서 추진하는 프리미엄 다이닝 운영 프로젝트입니다. 사업 구조와 파트너 역할, 예상 일정은 GLI가 직접 구성하고 검토합니다.",
    trustScore: 73,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    updatedAt: "2026-07-29T13:00:00+07:00",
    detailFacts: [
      { label: "기회 유형", value: "운영 프로젝트" },
      { label: "참여 방식", value: "공동 사업 협의" },
      { label: "예상 일정", value: "조사 예정" },
      { label: "파트너 역할", value: "조사 예정" },
    ],
    strengths: ["GLI 직접 발굴", "현지 운영 파트너 검토", "브랜드 확장 가능성"],
    checks: ["사업 계획", "운영 주체", "손익 및 계약 구조"],
  },
  {
    id: "GLI-PJ-VN-402",
    country: "Vietnam",
    countryCode: "VN",
    city: "Da Nang",
    district: "Son Tra",
    transaction: "sale",
    propertyType: "villa",
    assetCategory: "project",
    categoryLabel: "프로젝트",
    offerLabel: "공동 개발",
    priceLabel: "$350,000부터",
    cardMeta: "웰니스 리트리트 · 개발 및 운영",
    bedrooms: 0,
    bathrooms: 0,
    title: "Da Nang wellness retreat project",
    price: 350000,
    currency: "USD",
    areaSqm: 0,
    image:
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=84",
    summary:
      "다낭 해안 생활권의 웰니스 리트리트 개발·운영 프로젝트 후보입니다. 부지, 인허가, 운영 브랜드와 투자 구조는 단계별 GLI 검토 대상으로 관리합니다.",
    trustScore: 68,
    trustStatus: "PRELIMINARY",
    isGliDirect: true,
    updatedAt: "2026-07-18T09:00:00+07:00",
    detailFacts: [
      { label: "기회 유형", value: "개발 및 운영" },
      { label: "대상 지역", value: "다낭 손트라" },
      { label: "부지 및 인허가", value: "조사 예정" },
      { label: "운영 브랜드", value: "조사 예정" },
    ],
    strengths: ["웰니스 관광 수요", "해안 생활권", "개발·운영 통합 후보"],
    checks: ["부지 권리", "개발 인허가", "운영 브랜드 계약"],
  },
];

export function findCuratedOpportunity(id: string): Asset | undefined {
  return curatedOpportunities.find((asset) => asset.id === id);
}

export function listCuratedOpportunities(category?: AssetCategory): Asset[] {
  return category
    ? curatedOpportunities.filter((asset) => asset.assetCategory === category)
    : curatedOpportunities;
}
