import type { Asset } from "./assets.ts";

// Partner assets are published from the supplied document set at the document's
// stated reference point. They are not presented as live inventory. A future
// admin workflow must replace these fixtures with versioned Project, Offering,
// Evidence, and Partner records while preserving the original document date.
export const partnerAssets: Asset[] = [
  {
    id: "GLI-PT-VN-501",
    country: "Vietnam",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    district: "Binh Duong Ward",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "프로젝트 안내",
    priceLabel: "자료상 가격 미기재",
    cardMeta: "2개 동 · 517세대 · 2027년 4분기 인도 예정",
    bedrooms: 2,
    bathrooms: 2,
    title: "Orchard Grand at Sycamore",
    price: 0,
    currency: "VND",
    areaSqm: 75,
    image: "/partner-assets/orchard-grand.jpg",
    summary:
      "CapitaLand Development Vietnam과 UOA Group이 조성하는 Sycamore 마스터 개발의 주거 프로젝트입니다. 2개 동, 517세대와 약 99개의 편의시설이 계획되어 있습니다.",
    trustScore: 84,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "자료 기준일 미표기",
    publicationBasis: "Sycamore Orchard Grand 프로젝트 브로슈어",
    updatedAt: "2025-01-01T00:00:00+07:00",
    detailFacts: [
      { label: "프로젝트 규모", value: "2개 동 · 517세대" },
      { label: "대표 타입", value: "2BR 약 75㎡부터" },
      { label: "소유권 안내", value: "외국인 50년 표기" },
      { label: "자료 기준", value: "발행일 미표기" },
    ],
    strengths: ["대형 마스터 개발", "다양한 주거 타입", "예정 인도일 표기"],
    checks: ["현재 가격", "잔여 물량", "외국인 배정 가능 수량"],
  },
  {
    id: "GLI-PT-VN-502",
    country: "Vietnam",
    countryCode: "VN",
    city: "Ba Ria-Vung Tau",
    district: "Ho Tram",
    transaction: "sale",
    propertyType: "villa",
    assetCategory: "leisure",
    categoryLabel: "레저형",
    offerLabel: "리조트 프로젝트 안내",
    priceLabel: "자료상 가격 미기재",
    cardMeta: "빌라·콘도텔 · Fusion 운영 표기",
    bedrooms: 2,
    bathrooms: 2,
    title: "Ixora Ho Tram by Fusion",
    price: 0,
    currency: "VND",
    areaSqm: 51,
    image: "/partner-assets/ixora-ho-tram.jpg",
    summary:
      "The Grand Ho Tram 내 해변형 빌라·콘도텔 프로젝트입니다. 브로슈어와 SPA·임대계약서 양식을 함께 확보했으며, 수익 프로그램은 별도 계약 조건 확인을 전제로 안내합니다.",
    trustScore: 86,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "2024년 브로슈어·계약서 양식 기준",
    publicationBasis: "Ixora 2 브로슈어, SPA 및 임대계약서 양식",
    updatedAt: "2024-03-16T00:00:00+07:00",
    detailFacts: [
      { label: "상품 유형", value: "빌라·콘도텔" },
      { label: "문서상 토지 기간", value: "2058년 3월까지" },
      { label: "예상 인도", value: "2026년 3월 ±6개월" },
      { label: "자료 기준", value: "2024년 자료" },
    ],
    strengths: ["해변 리조트 입지", "계약서 구조 확보", "운영사 표기 자료"],
    checks: ["현재 가격·재고", "Rental Pool 최종 계약", "현재 인도 상태"],
  },
  {
    id: "GLI-PT-VN-503",
    country: "Vietnam",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    district: "Thu Thiem",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "분양 기준가격",
    priceLabel: "USD 7,000/㎡",
    cardMeta: "2개 동 · 300세대 · 상가·타운하우스 포함",
    bedrooms: 1,
    bathrooms: 1,
    title: "Thu Thiem Zeit River",
    price: 7000,
    currency: "USD",
    areaSqm: 60.62,
    image: "/partner-assets/thu-thiem-zeit-river.jpg",
    summary:
      "Thu Thiem New Urban Area Lot 3-11의 주거·상업 복합 프로젝트입니다. 2개 동과 약 300세대, 상가·타운하우스를 포함하는 복합 주거 환경으로 구성됩니다.",
    trustScore: 74,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "자료 내 2024년 인도 계획 기준",
    publicationBasis: "Thu Thiem GS 사업계획 자료",
    updatedAt: "2023-01-01T00:00:00+07:00",
    detailFacts: [
      { label: "대지면적", value: "9,125.8㎡" },
      { label: "구성", value: "25층·32층, 300세대" },
      { label: "가격 기준", value: "USD 7,000/㎡, VAT 제외" },
      { label: "자료 기준", value: "과거 분양자료" },
    ],
    strengths: ["Thu Thiem 핵심 입지", "다양한 타입 구성", "프로젝트 자료 확보"],
    checks: ["현재 준공·인도 상태", "현재 가격·재고", "외국인 쿼터"],
  },
  {
    id: "GLI-PJ-VN-504",
    country: "Vietnam",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    district: "Thu Thiem",
    transaction: "sale",
    propertyType: "house",
    assetCategory: "project",
    categoryLabel: "프로젝트",
    offerLabel: "개발 투자기회",
    priceLabel: "투자 조건 협의",
    cardMeta: "Lot 4-26·3-14 · 주거·상업 복합 개발",
    bedrooms: 0,
    bathrooms: 0,
    title: "Thu Thiem Lots 4-26 & 3-14 Development",
    price: 0,
    currency: "USD",
    areaSqm: 24818.54,
    image: "/partner-assets/thu-thiem-development.jpg",
    summary:
      "Thu Thiem의 Lot 4-26과 Lot 3-14를 단계적으로 개발하는 도시개발 투자기회입니다. 주거와 상업 기능이 결합된 복합 프로젝트로 계획되어 있습니다.",
    trustScore: 72,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "2023년 사업계획 기준",
    publicationBasis: "투티엠 사업계획서 및 수지분석 자료",
    updatedAt: "2023-01-01T00:00:00+07:00",
    detailFacts: [
      { label: "기회 유형", value: "도시개발 프로젝트" },
      { label: "대상 부지", value: "Lot 4-26 · Lot 3-14" },
      { label: "사업계획", value: "주거·상업 복합" },
      { label: "자료 기준", value: "2023년 사업계획" },
    ],
    strengths: ["Thu Thiem 개발 입지", "단계별 사업계획", "수지분석 자료 확보"],
    checks: ["현재 토지권리", "현재 인허가", "최신 사업·투자 조건"],
  },
  {
    id: "GLI-PJ-VN-505",
    country: "Vietnam",
    countryCode: "VN",
    city: "Con Dao",
    district: "Ben Dam",
    transaction: "sale",
    propertyType: "villa",
    assetCategory: "project",
    categoryLabel: "프로젝트",
    offerLabel: "개발 투자기회",
    priceLabel: "투자 조건 협의",
    cardMeta: "7.24ha · 호텔 106실 · 빌라 60동 계획",
    bedrooms: 0,
    bathrooms: 0,
    title: "Con Dao Vietnam-Russia Eco Resort",
    price: 0,
    currency: "USD",
    areaSqm: 72414.24,
    image: "/partner-assets/con-dao-resort.jpg",
    summary:
      "Con Dao의 5성급 친환경 리조트 개발 프로젝트입니다. 제공 자료는 1/500 계획 조정 제안 단계의 호텔 106실과 빌라 60동 계획을 담고 있습니다.",
    trustScore: 75,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "2025년 11월 제안자료 기준",
    publicationBasis: "Vietnam Con Dao 1/500 계획 제안자료",
    updatedAt: "2025-11-01T00:00:00+07:00",
    detailFacts: [
      { label: "부지면적", value: "72,414.24㎡" },
      { label: "계획 규모", value: "호텔 106실 · 빌라 60동" },
      { label: "개발 단계", value: "계획 조정 제안" },
      { label: "자료 기준", value: "2025년 11월" },
    ],
    strengths: ["Con Dao 해안 입지", "리조트 개발 계획", "토지이용 계획자료"],
    checks: ["최종 1/500 승인", "토지권리", "개발·운영 및 투자조건"],
  },
  {
    id: "GLI-PT-PH-506",
    country: "Philippines",
    countryCode: "PH",
    city: "Metro Manila & Cebu",
    district: "Multiple Locations",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "문서상 프로젝트 가격 범위",
    priceLabel: "PHP 4M~57M",
    cardMeta: "Galleria·Brighton·McKinley 주거 포트폴리오",
    bedrooms: 1,
    bathrooms: 1,
    title: "RLC Philippines Residential Portfolio",
    price: 4000000,
    maxPrice: 57000000,
    currency: "PHP",
    areaSqm: 0,
    image: "/partner-assets/rlc-portfolio.jpg",
    summary:
      "Galleria·Brighton·McKinley를 포함한 필리핀 주요 주거 프로젝트 포트폴리오입니다. 도시형 레지던스부터 복합단지 주거 상품까지 함께 살펴볼 수 있습니다.",
    trustScore: 70,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "자료 기준일 미표기",
    publicationBasis: "RLC projects and details 포트폴리오",
    updatedAt: "2025-01-01T00:00:00+08:00",
    detailFacts: [
      { label: "대표 프로젝트", value: "Galleria · Brighton · McKinley" },
      { label: "문서상 가격 범위", value: "PHP 4M~57M" },
      { label: "대상 지역", value: "Metro Manila · Cebu 등" },
      { label: "자료 기준", value: "발행일 미표기" },
    ],
    strengths: ["다지역 프로젝트 구성", "다양한 가격 범위", "파트너 포트폴리오 자료"],
    checks: ["프로젝트별 현재 재고", "가격-프로젝트 대응", "판매완료 항목 구분"],
  },
  {
    id: "GLI-PT-PH-507",
    country: "Philippines",
    countryCode: "PH",
    city: "Mandaue City",
    district: "Ouano Avenue",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "프로젝트 안내",
    priceLabel: "자료상 가격 미기재",
    cardMeta: "1BR·2BR·3BR·Penthouse · 주거·상업 복합",
    bedrooms: 1,
    bathrooms: 1,
    title: "Mantawi Residences Tower 1",
    price: 0,
    currency: "PHP",
    areaSqm: 0,
    image: "/partner-assets/mantawi-residences.jpg",
    summary:
      "Mandaue City의 주거·상업 복합 프로젝트입니다. 제공된 Fact Sheet와 eBook을 기준으로 유닛 마감재, 설비, 공용시설과 주거 편의 정보를 구성했습니다.",
    trustScore: 81,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "2025년 4월 8일 자료 기준",
    publicationBasis: "Mantawi Tower 1 Fact Sheet 및 eBook",
    updatedAt: "2025-04-08T00:00:00+08:00",
    detailFacts: [
      { label: "프로젝트 유형", value: "주거·상업 복합" },
      { label: "유닛 구성", value: "1BR~Penthouse" },
      { label: "공용시설", value: "수영장·업무라운지·피트니스" },
      { label: "자료 기준", value: "2025년 4월 8일" },
    ],
    strengths: ["상세 Fact Sheet", "다양한 공용시설", "실내 마감자료 확보"],
    checks: ["현재 가격·재고", "전체 세대·면적", "인도 예정일"],
  },
  {
    id: "GLI-PT-MY-508",
    country: "Malaysia",
    countryCode: "MY",
    city: "Kuala Lumpur",
    district: "Jalan Ampang",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "commercial",
    categoryLabel: "상업용",
    offerLabel: "SOHO·SOVO 프로젝트 안내",
    priceLabel: "자료상 가격 미기재",
    cardMeta: "Freehold · 3개 동 · 2,215실 · 2029년 완공 예정",
    bedrooms: 1,
    bathrooms: 1,
    title: "Armani Hallson KLCC",
    price: 0,
    currency: "MYR",
    areaSqm: 37.72,
    image: "/partner-assets/armani-hallson.jpg",
    summary:
      "Jalan Ampang의 Freehold SOHO·SOVO 복합 프로젝트입니다. 3개 동, 총 2,215실과 2029년 완공 계획으로 구성됩니다.",
    trustScore: 82,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "V11 브로슈어 기준·발행일 미표기",
    publicationBasis: "Armani Hallson KLCC V11 브로슈어",
    updatedAt: "2025-01-01T00:00:00+08:00",
    detailFacts: [
      { label: "권리", value: "Freehold" },
      { label: "구성", value: "SOHO 1개 동 · SOVO 2개 동" },
      { label: "예정 완공", value: "2029년" },
      { label: "자료 기준", value: "V11 브로슈어" },
    ],
    strengths: ["KLCC 접근성", "Freehold 표기", "상세 유닛 구성"],
    checks: ["현재 가격·재고", "광고허가", "용도별 거주·임대 조건"],
  },
  {
    id: "GLI-PT-MY-509",
    country: "Malaysia",
    countryCode: "MY",
    city: "Kuala Lumpur",
    district: "Jalan Tun Razak",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "문서상 분양가격",
    priceLabel: "RM 1,352,000~3,174,000",
    cardMeta: "Leasehold 99년 · 490세대 · 2028년 8월 완공 예정",
    bedrooms: 1,
    bathrooms: 1,
    title: "Golden Crown Residence",
    price: 1352000,
    maxPrice: 3174000,
    currency: "MYR",
    areaSqm: 58,
    image: "/partner-assets/golden-crown/facade.jpg",
    images: [
      "/partner-assets/golden-crown/facade.jpg",
      "/partner-assets/golden-crown/exterior.jpg",
      "/partner-assets/golden-crown/lobby.jpg",
      "/partner-assets/golden-crown/bedroom.jpg",
      "/partner-assets/golden-crown/pool.jpg",
      "/partner-assets/golden-crown/gym.jpg",
      "/partner-assets/golden-crown/bbq.jpg",
      "/partner-assets/golden-crown/pavilion.jpg",
    ],
    publicResources: [
      {
        label: "Golden Crown Residence 공식 홈페이지",
        url: "https://gsklproperty.com/portfolio/golden-crown-residence/",
        type: "website",
      },
    ],
    summary:
      "Jalan Tun Razak의 호텔·오피스·레지던스 복합 프로젝트입니다. 제공 브로슈어에 개발면허, 광고허가, 권리기간, 가격 범위와 예상 완공일이 함께 기재되어 있습니다.",
    trustScore: 88,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "제공 브로슈어·허가 정보 기준",
    publicationBasis: "Golden Crown Residence 영문 브로슈어",
    updatedAt: "2025-01-01T00:00:00+08:00",
    detailFacts: [
      { label: "권리", value: "99년 Leasehold" },
      { label: "레지던스", value: "490세대 · 58~95㎡" },
      { label: "예상 완공", value: "2028년 8월" },
      { label: "자료 기준", value: "제공 브로슈어" },
    ],
    strengths: ["가격·허가 정보 표기", "KL 중심 입지", "복합시설 구성"],
    checks: ["현재 가격·재고", "외국인 구매 기준", "관리비·납부 일정"],
  },
  {
    id: "GLI-PT-MY-510",
    country: "Malaysia",
    countryCode: "MY",
    city: "Kuala Lumpur",
    district: "Golden Triangle",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "프로젝트 안내",
    priceLabel: "자료상 가격 미기재",
    cardMeta: "Pavilion KL 연결 · Studio~3BR",
    bedrooms: 1,
    bathrooms: 1,
    title: "Pavilion Square",
    price: 0,
    currency: "MYR",
    areaSqm: 46.8,
    image: "/partner-assets/pavilion-square.jpg",
    summary:
      "Kuala Lumpur Golden Triangle에서 Pavilion KL과 연결되는 주거 프로젝트입니다. 도심 핵심 상권과 직접 연결되는 입지와 다양한 주거 타입을 제공합니다.",
    trustScore: 80,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "제공 프로젝트 브리프 기준",
    publicationBasis: "Pavilion Square 프로젝트 브리프·GLI 게시 승인",
    updatedAt: "2025-01-01T00:00:00+08:00",
    detailFacts: [
      { label: "입지", value: "Kuala Lumpur Golden Triangle" },
      { label: "대표 타입", value: "Studio 504 sqft부터" },
      { label: "연결 시설", value: "Pavilion KL" },
      { label: "자료 기준", value: "제공 프로젝트 브리프" },
    ],
    strengths: ["Pavilion KL 연결", "도심 핵심 입지", "다양한 주거 타입"],
    checks: ["현재 가격·재고", "공식 외부용 자료", "권리·완공 일정"],
  },
  {
    id: "GLI-PT-MY-511",
    country: "Malaysia",
    countryCode: "MY",
    city: "Kuala Lumpur",
    district: "KLCC",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "문서상 분양가격",
    priceLabel: "RM 1,976,400~8,020,800",
    cardMeta: "Freehold · Residence·Hotel · 2029년 1월 완공 예정",
    bedrooms: 1,
    bathrooms: 1,
    title: "CloutHaus KLCC",
    price: 1976400,
    maxPrice: 8020800,
    currency: "MYR",
    areaSqm: 51,
    image: "/partner-assets/clouthaus.jpg",
    summary:
      "Petronas Towers 조망을 강조한 KLCC 레지던스·호텔 프로젝트입니다. 도심 생활 편의와 호텔형 서비스가 결합된 복합 주거 상품입니다.",
    trustScore: 79,
    trustStatus: "NEEDS_ATTENTION",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "광고허가 2025년 7월 30일까지 표기",
    publicationBasis: "TA Global CloutHaus 영문 브로슈어",
    updatedAt: "2025-07-30T00:00:00+08:00",
    detailFacts: [
      { label: "권리", value: "Freehold" },
      { label: "문서상 규모", value: "Tower 2 615실 · Menara 1 242실" },
      { label: "예상 완공", value: "2029년 1월" },
      { label: "자료 기준", value: "2025년 7월 허가 표기" },
    ],
    strengths: ["KLCC 핵심 입지", "Freehold 표기", "가격·타입 자료 확보"],
    checks: ["갱신된 광고허가", "현재 가격·재고", "서비스 브랜드 확정"],
  },
  {
    id: "GLI-PT-MY-512",
    country: "Malaysia",
    countryCode: "MY",
    city: "Kuala Lumpur",
    district: "Bukit Bintang",
    transaction: "sale",
    propertyType: "condo",
    assetCategory: "residential",
    categoryLabel: "주거용",
    offerLabel: "프로젝트 안내",
    priceLabel: "자료상 가격 미기재",
    cardMeta: "도심 레지던스 · 시설층·옥상 수영장 자료",
    bedrooms: 1,
    bathrooms: 1,
    title: "Times Square 2 Kuala Lumpur",
    price: 0,
    currency: "MYR",
    areaSqm: 0,
    image: "/partner-assets/times-square-2.jpg",
    summary:
      "Kuala Lumpur 도심의 Times Square 2 레지던스 프로젝트입니다. 제공된 2025년 축약 브로슈어에서 확인되는 프로젝트 이미지와 시설계획을 기준으로 게시합니다.",
    trustScore: 65,
    trustStatus: "REVIEWING",
    isGliDirect: true,
    originLabel: "GLI 검증",
    documentDateLabel: "2025년 11월 26일 자료 기준",
    publicationBasis: "Times Square 2 축약 브로슈어",
    updatedAt: "2025-11-26T00:00:00+08:00",
    detailFacts: [
      { label: "프로젝트 유형", value: "도심 레지던스" },
      { label: "확인 시설", value: "시설층 · 옥상 수영장" },
      { label: "상세 규모", value: "조사 예정" },
      { label: "자료 기준", value: "2025년 11월 26일" },
    ],
    strengths: ["도심 입지", "시설층 자료", "프로젝트 렌더링 확보"],
    checks: ["개발사·권리", "전체 규모·타입", "현재 가격·완공일"],
  },
];
